INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Basic', 'Basic Yahoo', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Pascal', 'Basic Pascal', NOW());
