INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Basic', 'Basic Yahoo', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World C', 'Seashore Raiders', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Delphi', 'Pythis of Delhi', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Fortran', 'Also Ran', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Go', 'Inspector Go Go', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Java', 'Mr. Coffee', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Pascal', 'Dr Rascillian', NOW());
INSERT INTO BOOK(TITLE,AUTHOR,SUBMISSION_DATE) VALUES ('Hello World Rust', 'Rust Boat', NOW());
